DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE CONTACT (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
     , PRIMARY KEY (ID)
);


-- Note that the CONTACT_ID Foreign Key is Nullable 
-- in the Book table as a Book is not required 
-- to have been checked out by a Contact
CREATE TABLE BOOK (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , CONTACT_ID INT
     , PUBLISHER VARCHAR(60)
     , DATE_OF_PUBLICATION DATE
     , DESCRIPTION VARCHAR(2000)
     , PHOTO BLOB
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_BOOK (NAME)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_BOOK_1 FOREIGN KEY (CONTACT_ID)
                  REFERENCES CONTACT (ID)
);

