DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , PUBLISHER VARCHAR(60)
     , DATE_OF_PUBLICATION DATE
     , DESCRIPTION VARCHAR(2000)
     , PHOTO BLOB
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_BOOK (NAME)
     , PRIMARY KEY (ID)
);

